version: 2
models:
  - name: srv_hipotese_gestor_esforco_rj
    description: "Tabela final para testar a relação entre qualificação da gestão e IED no RJ."
    columns:
      - name: co_entidade
        description: "Código INEP da escola."
        tests:
          - unique
          - not_null
      - name: ied
        description: "Índice de Esforço Docente (1 a 6). Quanto maior, mais sobrecarga."
      - name: score_qualificacao_gestor
        description: "Score composto (0 a 1) de escolaridade e forma de acesso ao cargo."