with

source as (
    select * from {{ source('raw_data', 'tabela_gestor_escolar_2025') }}
),

renamed_and_casted as (
    select
        cast(nu_ano_censo as int) as nu_ano_censo,
        cast(co_entidade as varchar) as co_entidade,
        
        qt_gest_bas,
        qt_gest_bas_fem,
        qt_gest_bas_masc,
        qt_gest_bas_nd,
        qt_gest_bas_branca,
        qt_gest_bas_preta,
        qt_gest_bas_parda,
        qt_gest_bas_amarela,
        qt_gest_bas_indigena,
        qt_gest_bas_nacio_brasileira,
        qt_gest_bas_nacio_estrang,
        qt_gest_bas_0_24,
        qt_gest_bas_25_29,
        qt_gest_bas_30_39,
        qt_gest_bas_40_49,
        qt_gest_bas_50_54,
        qt_gest_bas_55_59,
        qt_gest_bas_60_mais,
        qt_gest_bas_pcd,
        qt_gest_bas_zr_urb,
        qt_gest_bas_zr_rur,
        qt_gest_bas_zr_na,
        qt_gest_bas_esco_ef,
        qt_gest_bas_esco_em,
        qt_gest_bas_esco_sup_grad,
        qt_gest_bas_esco_sup_grad_licen,
        qt_gest_bas_esco_sup_grad_slicen,
        qt_gest_bas_esco_sup_pos_espec,
        qt_gest_bas_esco_sup_pos_mestra,
        qt_gest_bas_esco_sup_pos_douto,
        qt_gest_bas_esco_sup_pos_nenhum,
        qt_gest_bas_vinculo_concur,
        qt_gest_bas_vinculo_contra,
        qt_gest_bas_vinculo_terceir,
        qt_gest_bas_vinculo_clt,
        qt_gest_bas_diretor,
        qt_gest_bas_outro,
        qt_gest_bas_acesso_cargo_prop,
        qt_gest_bas_acesso_cargo_indic,
        qt_gest_bas_acesso_cargo_sel,
        qt_gest_bas_acesso_cargo_conc,
        qt_gest_bas_acesso_cargo_eleic,
        qt_gest_bas_acesso_cargo_p_sel,
        qt_gest_bas_acesso_cargo_outro,
        qt_gest_bas_espec_cre,
        qt_gest_bas_espec_pre_escola,
        qt_gest_bas_espec_anos_iniciais,
        qt_gest_bas_espec_anos_finais,
        qt_gest_bas_espec_ens_medio,
        qt_gest_bas_espec_eja,
        qt_gest_bas_espec_ed_especial,
        qt_gest_bas_espec_bil_surdos,
        qt_gest_bas_espec_ed_indigena,
        qt_gest_bas_espec_campo,
        qt_gest_bas_espec_ambiental,
        qt_gest_bas_espec_dir_humanos,
        qt_gest_bas_espec_div_sexual,
        qt_gest_bas_espec_dir_adolesc,
        qt_gest_bas_espec_afro,
        qt_gest_bas_espec_gestao,
        qt_gest_bas_espec_educ_tic,
        qt_gest_bas_espec_outros,
        qt_gest_bas_espec_nenhum
        
    from source
)

select * from renamed_and_casted